name: Deploy Fabric Notebooks

on:
  push:
    branches: [dev]
    paths: 
      - 'src/stacktrend/notebooks/**'
      - 'src/stacktrend/utils/deploy_notebooks.py'
      - 'src/stacktrend/config/settings.py'
      - '.github/workflows/deploy-fabric-notebooks.yml'

jobs:
  deploy-notebooks:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        
    - name: Deploy to Fabric
      env:
        FABRIC_TENANT_ID: ${{ secrets.FABRIC_TENANT_ID }}
        FABRIC_CLIENT_ID: ${{ secrets.FABRIC_CLIENT_ID }}
        FABRIC_CLIENT_SECRET: ${{ secrets.FABRIC_CLIENT_SECRET }}
        FABRIC_WORKSPACE_ID: ${{ secrets.FABRIC_WORKSPACE_ID }}
      run: |
        python -m src.stacktrend.utils.deploy_notebooks
        
    - name: Report deployment status
      run: |
        echo "✅ Notebook deployment completed successfully!"
